# fly.toml app configuration file generated for redtangle on 2023-11-14T20:08:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redtangle"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
